import { moment, normalizePath, TFile } from 'obsidian';
import type TPSGlobalContextMenuPlugin from '../main';
import * as logger from '../logger';
import type { DailyNoteConfigurationSnapshot } from './file-naming-service';
import {
  inspectTemplateProtectionSource,
  stripTemplateProtectionTagFromSource,
} from '../utils/template-protection';
import type { TemplateProtectionInspection } from '../utils/template-protection';
import { getDailyNotePathDateCandidate } from '../utils/daily-note-creation';

export type DailyNoteTemplateInstanceCleanupStatus =
  | 'stripped'
  | 'unmarked'
  | 'not-configured-output'
  | 'no-configured-template'
  | 'configured-template-source'
  | 'configured-template-unavailable'
  | 'configured-template-unprotected'
  | 'configured-template-unsafe'
  | 'output-unsafe'
  | 'configuration-changed'
  | 'file-changed'
  | 'settlement-timeout'
  | 'process-unavailable'
  | 'cancelled'
  | 'failed';

export type DailyNoteTemplateInstanceCleanupResult = {
  status: DailyNoteTemplateInstanceCleanupStatus;
  file: TFile | null;
};

type CleanupTiming = {
  minimumSettleDelayMs: number;
  stableReadWindowMs: number;
  pollIntervalMs: number;
  timeoutMs: number;
};

const DEFAULT_CLEANUP_TIMING: CleanupTiming = {
  // Templater's create hook is delayed by 300 ms. Keep this gate later than
  // that hook so a busy device cannot make TPS sanitize the source bytes that
  // Templater is still about to consume.
  minimumSettleDelayMs: 700,
  stableReadWindowMs: 100,
  pollIntervalMs: 50,
  timeoutMs: 5_000,
};

function normalizeFolder(value: unknown): string {
  return normalizePath(String(value ?? '').trim()).replace(/^\/+|\/+$/gu, '');
}

function normalizeTemplatePath(value: unknown): string {
  return normalizePath(String(value ?? '').trim()).replace(/^\/+|\/+$/gu, '');
}

function configurationFingerprint(snapshot: DailyNoteConfigurationSnapshot): string {
  return [
    normalizeFolder(snapshot.folder),
    String(snapshot.format || '').trim() || 'YYYY-MM-DD',
    normalizeTemplatePath(snapshot.template),
  ].join('\u0000');
}

/**
 * Return a date only when the path is exactly one output generated by the
 * supplied Daily Notes folder/format pair. Frontmatter never participates, so
 * a copied stale `scheduled` value cannot turn an unrelated note into a target.
 */
export function getConfiguredDailyNoteOutputPathDate(
  filePath: string,
  snapshot: Pick<DailyNoteConfigurationSnapshot, 'folder' | 'format'>,
): string | null {
  const folder = normalizeFolder(snapshot.folder);
  const format = String(snapshot.format || '').trim() || 'YYYY-MM-DD';
  const candidate = getDailyNotePathDateCandidate(filePath, folder);
  if (!candidate) return null;
  const momentLib = ((globalThis as any)?.window?.moment || moment) as any;
  const parsed = momentLib(candidate, format, true);
  if (!parsed?.isValid?.() || !parsed.isValid()) return null;
  const isoDate = parsed.format('YYYY-MM-DD');
  const iso = momentLib(isoDate, 'YYYY-MM-DD', true);
  if (!iso?.isValid?.() || !iso.isValid()) return null;
  const expectedRelativePath = iso.format(format);
  const expectedPath = normalizePath(
    folder ? `${folder}/${expectedRelativePath}.md` : `${expectedRelativePath}.md`,
  );
  return normalizePath(filePath) === expectedPath ? isoDate : null;
}

export function resolveConfiguredDailyNoteTemplateFile(
  plugin: Pick<TPSGlobalContextMenuPlugin, 'app'>,
  templatePath: unknown,
): TFile | null {
  const normalized = normalizeTemplatePath(templatePath);
  if (!normalized) return null;
  const candidates = normalized.toLocaleLowerCase().endsWith('.md')
    ? [normalized]
    : [normalized, `${normalized}.md`];
  for (const candidatePath of candidates) {
    const candidate = plugin.app.vault.getAbstractFileByPath(candidatePath);
    if (candidate instanceof TFile) return candidate;
  }
  const linked = plugin.app.metadataCache.getFirstLinkpathDest?.(
    normalized.replace(/\.md$/iu, ''),
    '',
  );
  return linked instanceof TFile ? linked : null;
}

/**
 * Handles creation-time template identity cleanup: an exact configured Daily
 * Note instance inherits the source marker, then loses only
 * that marker once Core Daily Notes/Periodic Notes and Templater have settled.
 * No existing-file sweep is performed.
 */
export class DailyNoteTemplateInstanceCleanupService {
  private readonly timing: CleanupTiming;
  private readonly pendingFiles = new WeakSet<TFile>();
  private disposed = false;

  constructor(
    private readonly plugin: TPSGlobalContextMenuPlugin,
    timing: Partial<CleanupTiming> = {},
  ) {
    this.timing = { ...DEFAULT_CLEANUP_TIMING, ...timing };
  }

  dispose(): void {
    this.disposed = true;
  }

  schedule(
    file: TFile,
    onComplete?: (result: DailyNoteTemplateInstanceCleanupResult) => void | Promise<void>,
  ): void {
    if (this.disposed || this.pendingFiles.has(file)) return;
    this.pendingFiles.add(file);
    const createdAt = Date.now();
    void this.cleanupCreatedFile(file, createdAt)
      .then(async (result) => {
        if (!this.disposed) await onComplete?.(result);
      })
      .catch((error) => {
        logger.warn('[TPS GCM] Daily Note template-instance cleanup failed', {
          path: file.path,
          error,
        });
      });
  }

  async cleanupCreatedFile(
    file: TFile,
    createdAt = Date.now(),
  ): Promise<DailyNoteTemplateInstanceCleanupResult> {
    if (this.disposed) return { status: 'cancelled', file: null };
    if (!(file instanceof TFile) || file.extension.toLocaleLowerCase() !== 'md') {
      return { status: 'not-configured-output', file: null };
    }

    try {
      await this.plugin.fileNamingService.whenDailyNoteConfigurationReady();
      if (this.disposed) return { status: 'cancelled', file: null };

      const initialSnapshot = this.plugin.fileNamingService.getDailyNoteConfigurationSnapshot();
      if (!initialSnapshot || !normalizeTemplatePath(initialSnapshot.template)) {
        return { status: 'no-configured-template', file };
      }
      if (!getConfiguredDailyNoteOutputPathDate(file.path, initialSnapshot)) {
        return { status: 'not-configured-output', file };
      }

      const initialTemplate = resolveConfiguredDailyNoteTemplateFile(this.plugin, initialSnapshot.template);
      if (!(initialTemplate instanceof TFile)) {
        return { status: 'configured-template-unavailable', file };
      }
      if (initialTemplate === file || normalizePath(initialTemplate.path) === normalizePath(file.path)) {
        return { status: 'configured-template-source', file };
      }
      const initialTemplateState = await this.inspectConfiguredTemplate(initialTemplate);
      if (initialTemplateState !== 'protected') {
        return {
          status: initialTemplateState === 'unsafe'
            ? 'configured-template-unsafe'
            : 'configured-template-unprotected',
          file,
        };
      }

      const settledFile = await this.waitForCreatedFileSettlement(file, createdAt);
      if (this.disposed) return { status: 'cancelled', file: null };
      if (!(settledFile instanceof TFile)) return { status: 'settlement-timeout', file: null };

      const currentSnapshot = this.plugin.fileNamingService.getDailyNoteConfigurationSnapshot();
      if (
        !currentSnapshot
        || configurationFingerprint(currentSnapshot) !== configurationFingerprint(initialSnapshot)
      ) {
        return { status: 'configuration-changed', file: settledFile };
      }
      if (!getConfiguredDailyNoteOutputPathDate(settledFile.path, currentSnapshot)) {
        return { status: 'file-changed', file: settledFile };
      }

      const currentTemplate = resolveConfiguredDailyNoteTemplateFile(this.plugin, currentSnapshot.template);
      if (!(currentTemplate instanceof TFile)) {
        return { status: 'configured-template-unavailable', file: settledFile };
      }
      if (currentTemplate === settledFile || normalizePath(currentTemplate.path) === normalizePath(settledFile.path)) {
        return { status: 'configured-template-source', file: settledFile };
      }
      const currentTemplateState = await this.inspectConfiguredTemplate(currentTemplate);
      if (currentTemplateState !== 'protected') {
        return {
          status: currentTemplateState === 'unsafe'
            ? 'configured-template-unsafe'
            : 'configured-template-unprotected',
          file: settledFile,
        };
      }

      const vault = this.plugin.app.vault as typeof this.plugin.app.vault & {
        process?: (target: TFile, processor: (source: string) => string) => Promise<unknown>;
      };
      if (typeof vault.process !== 'function') {
        return { status: 'process-unavailable', file: settledFile };
      }

      const mutationState: { inspection: TemplateProtectionInspection; changed: boolean } = {
        inspection: 'unprotected',
        changed: false,
      };
      await vault.process(settledFile, (currentSource) => {
        // Vault.process supplies current bytes at the mutation boundary. Never
        // replace a concurrent edit with an earlier read snapshot.
        mutationState.inspection = inspectTemplateProtectionSource(currentSource, this.plugin.settings);
        if (mutationState.inspection !== 'protected') return currentSource;
        const nextSource = stripTemplateProtectionTagFromSource(currentSource, this.plugin.settings);
        mutationState.changed = nextSource !== currentSource;
        return nextSource;
      });

      if (mutationState.inspection === 'unsafe') return { status: 'output-unsafe', file: settledFile };
      if (!mutationState.changed) return { status: 'unmarked', file: settledFile };
      logger.flow('DailyNote', 'external-template-marker-stripped', {
        path: settledFile.path,
        source: currentSnapshot.source,
      });
      return { status: 'stripped', file: settledFile };
    } catch (error) {
      logger.warn('[TPS GCM] Could not sanitize a newly created Daily Note template instance', {
        path: file.path,
        error,
      });
      return { status: 'failed', file: null };
    }
  }

  private async inspectConfiguredTemplate(
    templateFile: TFile,
  ): Promise<ReturnType<typeof inspectTemplateProtectionSource>> {
    try {
      const source = await this.plugin.app.vault.read(templateFile);
      return inspectTemplateProtectionSource(source, this.plugin.settings);
    } catch {
      return 'unsafe';
    }
  }

  private async waitForCreatedFileSettlement(
    file: TFile,
    createdAt: number,
  ): Promise<TFile | null> {
    const minimumSettleAt = Math.max(0, createdAt) + Math.max(0, this.timing.minimumSettleDelayMs);
    const deadline = Date.now() + Math.max(1, this.timing.timeoutMs);
    let priorSource: string | null = null;
    let stableSince = 0;

    while (!this.disposed && Date.now() <= deadline) {
      const now = Date.now();
      if (now < minimumSettleAt) {
        await this.delay(Math.min(this.timing.pollIntervalMs, minimumSettleAt - now));
        continue;
      }

      const liveFile = this.resolveLiveFile(file);
      if (!(liveFile instanceof TFile)) return null;
      if (this.isTemplaterFilePending(liveFile)) {
        priorSource = null;
        stableSince = 0;
        await this.delay(this.timing.pollIntervalMs);
        continue;
      }

      let currentSource = '';
      try {
        currentSource = await this.plugin.app.vault.read(liveFile);
      } catch {
        return null;
      }
      const observedAt = Date.now();
      if (currentSource !== priorSource) {
        priorSource = currentSource;
        stableSince = observedAt;
      } else if (observedAt - stableSince >= Math.max(0, this.timing.stableReadWindowMs)) {
        return liveFile;
      }
      await this.delay(this.timing.pollIntervalMs);
    }
    return null;
  }

  private resolveLiveFile(file: TFile): TFile | null {
    const live = this.plugin.app.vault.getFileByPath?.(file.path)
      ?? this.plugin.app.vault.getAbstractFileByPath(file.path);
    // A delete/recreate at the same path is a different creation and must not
    // inherit this operation's authority.
    return live instanceof TFile && live === file ? live : null;
  }

  private isTemplaterFilePending(file: TFile): boolean {
    const templater = (this.plugin.app as any)?.plugins?.getPlugin?.('templater-obsidian')
      ?? (this.plugin.app as any)?.plugins?.plugins?.['templater-obsidian'];
    const pendingFiles = templater?.templater?.files_with_pending_templates;
    return typeof pendingFiles?.has === 'function' && pendingFiles.has(file.path);
  }

  private async delay(milliseconds: number): Promise<void> {
    await new Promise<void>((resolve) => {
      globalThis.setTimeout(resolve, Math.max(1, milliseconds));
    });
  }
}
