const GENERATED_MARKER = '# Generated by TPS Home';

export function buildHomeWorkoutScopedBaseBody(sourceBody: string, selectedDate: string, sourcePath: string): string {
  const marker = `${GENERATED_MARKER} from ${sourcePath}. Do not edit directly.`;
  const sourceLines = String(sourceBody || '')
    .replace(/^# Generated by TPS Home[^\n]*\n/, '')
    .replace(/\s+$/u, '')
    .split(/\r?\n/);
  const viewsIndex = sourceLines.findIndex((line) => /^views:\s*$/.test(line));
  if (viewsIndex < 0) return `${marker}\n${sourceLines.join('\n')}\n`;

  const filterIndex = sourceLines.slice(0, viewsIndex).findIndex((line) => /^filters:\s*$/.test(line));
  const dateFilter = `    - workoutDate == date("${selectedDate}")`;
  if (filterIndex < 0) {
    return [
      marker,
      ...sourceLines.slice(0, viewsIndex),
      'filters:',
      '  and:',
      '    - or:',
      '        - kind == "workout"',
      '        - and:',
      '            - runKind == "run"',
      '            - or:',
      '                - runType == "workout"',
      '                - workflowType == "workout"',
      dateFilter,
      ...sourceLines.slice(viewsIndex),
      '',
    ].join('\n');
  }

  const prefix = sourceLines.slice(0, filterIndex);
  const existingFilterBody = sourceLines.slice(filterIndex + 1, viewsIndex)
    .filter((line) => !/^\s*-\s*workoutDate\s*==\s*date\("\d{4}-\d{2}-\d{2}"\)\s*$/.test(line));
  const firstContentIndex = existingFilterBody.findIndex((line) => line.trim());
  const hasTopLevelAnd = firstContentIndex >= 0 && /^  and:\s*$/.test(existingFilterBody[firstContentIndex]);
  const nextFilterBody = hasTopLevelAnd
    ? [...existingFilterBody, dateFilter]
    : wrapFilterBodyInAnd(existingFilterBody, dateFilter);

  return [
    marker,
    ...prefix,
    'filters:',
    ...nextFilterBody,
    ...sourceLines.slice(viewsIndex),
    '',
  ].join('\n');
}

function wrapFilterBodyInAnd(lines: string[], dateFilter: string): string[] {
  const firstContentIndex = lines.findIndex((line) => line.trim());
  if (firstContentIndex < 0) return ['  and:', dateFilter];
  return [
    '  and:',
    ...lines.map((line, index) => {
      if (!line.trim()) return line;
      if (index === firstContentIndex) return line.replace(/^  (\S)/, '    - $1');
      return `    ${line}`;
    }),
    dateFilter,
  ];
}
